FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

RUN apk add --no-cache curl \
    && addgroup -S relax && adduser -S relax -G relax

ARG JAR_FILE=target/relax-server-0.1.0-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

USER relax
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
